name: Flutter Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 최신 버전으로 변경
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.13.0'
      - run: flutter pub get
      - run: flutter build apk --debug
      - name: Upload APK
        uses: actions/upload-artifact@v4 # 최신 버전으로 변경
        with:
          name: ZombieGame-APK
          path: build/app/outputs/flutter-apk/app-debug.apk
